import type { SectionLabel } from './homepage-sections';

export const FESTIVAL_PAGE_UID = 'api::festival-page.festival-page';

export const FESTIVAL_SECTION_LABELS: SectionLabel[] = [
  { attr: 'enabled', label: 'Enable template', description: 'Assign Festival to the intended Store, Brand, Category or Bank, then enable this switch when ready. Off uses the owner’s normal page. On uses Festival even if sections are empty. Content is shared by this template; SEO comes from the selected owner entity, so edit SEO on that entity. Saves apply without a separate Publish step.' },
  { attr: 'title', label: 'Page title', description: 'Festival page title and breadcrumb label. Enter a meaningful campaign name; empty supplies no custom title. This does not replace the owner entity’s SEO title.' },
  { attr: 'countdown', label: '1 · Sale countdown', description: 'Optional countdown above the banner. Complete both dates, both phase labels and both button destinations before enabling. Empty or disabled means no clock; it disappears after the end time. Required fields cannot be left blank while enabled.' },
  { attr: 'hero', label: '2 · Festival banner', description: 'One desktop image fills the full viewport width on every screen. Height scales proportionally on smaller screens without cropping. Include badges in the image. No image means no banner; this does not affect template activation.' },
  { attr: 'offerSlider', label: '3 · Offer slider', description: 'Add and reorder Coupon slides (with or without a code). Empty overrides use the selected offer’s current content; no items means no slider.' },
  { attr: 'exploreCategories', label: '4 · Explore categories', description: 'Add and reorder any number of categories. Optional Coupon selections keep editorial order; empty selections use all latest live Coupons in that category. Search, filters and sorting run in the browser.' },
  { attr: 'savingsSection', label: '5 · Savings Coupons · Maximum 2', description: 'Select a maximum of 2 live Coupons. Empty or disabled hides these cards. Optional overrides change only these cards, not the source Coupon. Expand each row for title, description, logo, badge, button and T&C guidance. Desktop shows both cards; mobile uses a slider.' },
  { attr: 'productSection', label: '6 · Picked for you · Product Deals', description: 'Select and reorder Product Deals. Prices, discounts, product images and merchant logos use live Deal data. Optional title overrides change only this section. Category tiles use their generated /category-name-deals/ pages unless a URL override is entered; upload their artwork here. The listing shows the latest 50 live Deals by default, with 8 more per click. Configure optional brand, store and bank filter choices inside this section; only choices with matching live Deals appear. Discount ranges are generated automatically by the storefront.' },
  { attr: 'giftSection', label: '7 · Festival Gift Offers · Coupons', description: 'Select the exact Coupons to show and drag to reorder. Only selected live Coupons appear; an empty selection hides the slider. Categories control only the tiles below. Upload category artwork and optionally override category titles and Coupon display content. This section appears above Telegram.' },
  { attr: 'faq', label: '8 · Frequently asked questions', description: 'Enable and add questions and answers for this Festival page, then drag to reorder. A question is required per row. A blank answer leaves the question without answer content; complete both for a useful FAQ. Empty or disabled hides the section. The first FAQ with an answer opens initially. Heading is optional.' },
  { attr: 'popularSearches', label: '9 · Popular searches', description: 'Enable and select Stores, Brands, Categories or Banks to link below the FAQs. Leave an individual group empty to omit that group; nothing is auto-filled. With no valid selections, or when disabled, the whole section is hidden. Links use each entity’s current name and page URL; repeated links are shown once. Heading is optional.' },
];
